def korean_name_to_english(korean_name):
    """
    한글 이름을 영문 논문용 이름 형식으로 변환

    Args:
        korean_name (str): 한글 이름 (예: "홍길동", "김철수")

    Returns:
        list: 영문 이름 후보 리스트
    """

    # 성과 이름 분리 (첫 글자를 성으로 가정)
    if len(korean_name) < 2:
        return ["입력된 이름이 너무 짧습니다."]

    last_name = korean_name[0]
    first_name = korean_name[1:]

    # 한글 → 로마자 변환 매핑 (국립국어원 로마자 표기법 기준)
    romanization = {
        # 이름 음절
        "가": "ga",
        "각": "gak",
        "간": "gan",
        "갈": "gal",
        "감": "gam",
        "강": "gang",
        "개": "gae",
        "거": "geo",
        "건": "geon",
        "걸": "geol",
        "검": "geom",
        "겸": "gyeom",
        "경": "gyeong",
        "계": "gye",
        "고": "go",
        "곤": "gon",
        "골": "gol",
        "공": "gong",
        "관": "gwan",
        "광": "gwang",
        "괴": "goe",
        "교": "gyo",
        "구": "gu",
        "국": "guk",
        "군": "gun",
        "굉": "gwang",
        "권": "gwon",
        "규": "gyu",
        "균": "gyun",
        "귀": "gwi",
        "극": "geuk",
        "근": "geun",
        "글": "geul",
        "금": "geum",
        "급": "geup",
        "기": "gi",
        "길": "gil",
        "김": "gim",
        "깅": "ging",
        "나": "na",
        "낙": "nak",
        "난": "nan",
        "남": "nam",
        "낭": "nang",
        "내": "nae",
        "너": "neo",
        "녀": "nyeo",
        "년": "nyeon",
        "념": "nyeom",
        "녕": "nyeong",
        "노": "no",
        "녹": "nok",
        "논": "non",
        "뇌": "noe",
        "누": "nu",
        "눈": "nun",
        "뉴": "nyu",
        "다": "da",
        "단": "dan",
        "달": "dal",
        "담": "dam",
        "당": "dang",
        "대": "dae",
        "덕": "deok",
        "도": "do",
        "독": "dok",
        "돈": "don",
        "동": "dong",
        "두": "du",
        "둔": "dun",
        "득": "deuk",
        "등": "deung",
        "라": "ra",
        "락": "rak",
        "란": "ran",
        "랑": "rang",
        "래": "rae",
        "량": "ryang",
        "려": "ryeo",
        "력": "ryeok",
        "련": "ryeon",
        "렬": "ryeol",
        "렴": "ryeom",
        "령": "ryeong",
        "례": "rye",
        "로": "ro",
        "록": "rok",
        "론": "ron",
        "뢰": "roe",
        "료": "ryo",
        "룡": "ryong",
        "루": "ru",
        "류": "ryu",
        "륙": "ryuk",
        "륜": "ryun",
        "률": "ryul",
        "륭": "ryung",
        "르": "reu",
        "리": "ri",
        "린": "rin",
        "림": "rim",
        "립": "rip",
        "마": "ma",
        "막": "mak",
        "만": "man",
        "말": "mal",
        "망": "mang",
        "매": "mae",
        "맥": "maek",
        "먼": "meon",
        "명": "myeong",
        "모": "mo",
        "목": "mok",
        "몽": "mong",
        "무": "mu",
        "묵": "muk",
        "문": "mun",
        "물": "mul",
        "미": "mi",
        "민": "min",
        "밀": "mil",
        "바": "ba",
        "박": "bak",
        "반": "ban",
        "발": "bal",
        "방": "bang",
        "배": "bae",
        "백": "baek",
        "범": "beom",
        "법": "beop",
        "변": "byeon",
        "별": "byeol",
        "병": "byeong",
        "보": "bo",
        "복": "bok",
        "본": "bon",
        "봉": "bong",
        "부": "bu",
        "북": "buk",
        "분": "bun",
        "불": "bul",
        "비": "bi",
        "빈": "bin",
        "빙": "bing",
        "사": "sa",
        "삼": "sam",
        "상": "sang",
        "새": "sae",
        "색": "saek",
        "생": "saeng",
        "서": "seo",
        "석": "seok",
        "선": "seon",
        "섭": "seop",
        "성": "seong",
        "세": "se",
        "소": "so",
        "속": "sok",
        "손": "son",
        "솔": "sol",
        "송": "song",
        "수": "su",
        "숙": "suk",
        "순": "sun",
        "술": "sul",
        "숭": "sung",
        "슬": "seul",
        "승": "seung",
        "시": "si",
        "식": "sik",
        "신": "sin",
        "실": "sil",
        "심": "sim",
        "아": "a",
        "악": "ak",
        "안": "an",
        "알": "al",
        "암": "am",
        "압": "ap",
        "애": "ae",
        "야": "ya",
        "약": "yak",
        "양": "yang",
        "어": "eo",
        "언": "eon",
        "업": "eop",
        "여": "yeo",
        "역": "yeok",
        "연": "yeon",
        "열": "yeol",
        "염": "yeom",
        "영": "yeong",
        "예": "ye",
        "오": "o",
        "옥": "ok",
        "온": "on",
        "완": "wan",
        "왕": "wang",
        "외": "oe",
        "요": "yo",
        "용": "yong",
        "우": "u",
        "욱": "uk",
        "운": "un",
        "울": "ul",
        "웅": "ung",
        "원": "won",
        "월": "wol",
        "위": "wi",
        "유": "yu",
        "육": "yuk",
        "윤": "yun",
        "율": "yul",
        "융": "yung",
        "은": "eun",
        "을": "eul",
        "음": "eum",
        "응": "eung",
        "의": "ui",
        "이": "i",
        "익": "ik",
        "인": "in",
        "일": "il",
        "임": "im",
        "입": "ip",
        "자": "ja",
        "작": "jak",
        "잔": "jan",
        "장": "jang",
        "재": "jae",
        "저": "jeo",
        "적": "jeok",
        "전": "jeon",
        "절": "jeol",
        "점": "jeom",
        "정": "jeong",
        "제": "je",
        "조": "jo",
        "족": "jok",
        "존": "jon",
        "종": "jong",
        "좌": "jwa",
        "주": "ju",
        "죽": "juk",
        "준": "jun",
        "줄": "jul",
        "중": "jung",
        "즉": "jeuk",
        "증": "jeung",
        "지": "ji",
        "직": "jik",
        "진": "jin",
        "질": "jil",
        "집": "jip",
        "징": "jing",
        "차": "cha",
        "찬": "chan",
        "찰": "chal",
        "창": "chang",
        "채": "chae",
        "처": "cheo",
        "척": "cheok",
        "천": "cheon",
        "철": "cheol",
        "첨": "cheom",
        "청": "cheong",
        "체": "che",
        "초": "cho",
        "촉": "chok",
        "총": "chong",
        "최": "choe",
        "추": "chu",
        "축": "chuk",
        "춘": "chun",
        "출": "chul",
        "충": "chung",
        "취": "chwi",
        "측": "cheuk",
        "치": "chi",
        "친": "chin",
        "칠": "chil",
        "침": "chim",
        "타": "ta",
        "탁": "tak",
        "탄": "tan",
        "태": "tae",
        "택": "taek",
        "터": "teo",
        "토": "to",
        "통": "tong",
        "투": "tu",
        "특": "teuk",
        "파": "pa",
        "판": "pan",
        "팔": "pal",
        "패": "pae",
        "평": "pyeong",
        "페": "pe",
        "포": "po",
        "표": "pyo",
        "풍": "pung",
        "피": "pi",
        "필": "pil",
        "하": "ha",
        "학": "hak",
        "한": "han",
        "할": "hal",
        "함": "ham",
        "합": "hap",
        "항": "hang",
        "해": "hae",
        "핵": "haek",
        "향": "hyang",
        "허": "heo",
        "헌": "heon",
        "현": "hyeon",
        "혁": "hyeok",
        "형": "hyeong",
        "혜": "hye",
        "호": "ho",
        "혹": "hok",
        "홍": "hong",
        "화": "hwa",
        "환": "hwan",
        "활": "hwal",
        "황": "hwang",
        "회": "hoe",
        "효": "hyo",
        "후": "hu",
        "훈": "hun",
        "휘": "hwi",
        "희": "hui",
        "흥": "heung",
        # 성씨
        "김": "Kim",
        "이": "Lee",
        "박": "Park",
        "최": "Choi",
        "정": "Jung",
        "강": "Kang",
        "조": "Cho",
        "윤": "Yoon",
        "장": "Jang",
        "임": "Lim",
        "한": "Han",
        "오": "Oh",
        "서": "Seo",
        "신": "Shin",
        "권": "Kwon",
        "황": "Hwang",
        "안": "Ahn",
        "송": "Song",
        "류": "Ryu",
        "전": "Jeon",
        "홍": "Hong",
        "고": "Ko",
        "문": "Moon",
        "손": "Son",
        "양": "Yang",
        "배": "Bae",
        "백": "Baek",
        "허": "Heo",
        "남": "Nam",
        "심": "Sim",
        "노": "Noh",
        "하": "Ha",
        "곽": "Kwak",
        "성": "Sung",
        "차": "Cha",
        "주": "Joo",
        "우": "Woo",
        "구": "Koo",
        "라": "Ra",
        "진": "Jin",
    }

    # 성 변환
    last_name_eng = romanization.get(last_name, last_name.upper())

    # 이름 각 글자 변환
    first_name_parts = []
    for char in first_name:
        if char in romanization:
            part = romanization[char]
            # 이름의 경우 첫 글자를 대문자로
            first_name_parts.append(part.capitalize())
        else:
            first_name_parts.append(char)

    # 영문 이름 후보 생성
    candidates = []

    if len(first_name_parts) == 2:
        # 1. 이름1 이름2 성 (서양식)
        candidates.append(
            f"{first_name_parts[0]} {first_name_parts[1]} {last_name_eng}"
        )

        # 2. 이름1 이름2 성 (서양식)(하이픈)
        candidates.append(
            f"{first_name_parts[0]}-{first_name_parts[1]} {last_name_eng}"
        )

        # 3. 이름1 이름2 성 (서양식)(붙여쓰기)
        candidates.append(f"{first_name_parts[0]}{first_name_parts[1]} {last_name_eng}")

        # 4. 이름1 이름2 성 (서양식)(이니셜)
        candidates.append(
            f"{first_name_parts[0][0]}. {first_name_parts[1][0]}. {last_name_eng}"
        )

    elif len(first_name_parts) == 1:
        # 외자 이름
        candidates.append(f"{first_name_parts[0]} {last_name_eng}")

    else:
        # 3글자 이상 이름
        full_first = " ".join(first_name_parts)
        candidates.append(f"{full_first} {last_name_eng}")

    return candidates

# 사용 예시
if __name__ == "__main__":
    test_names = ["홍길동", "김철수", "이영희", "박지성"]
    
    for name in test_names:
        print(f"\n'{name}'의 영문 이름 후보:")
        print("-" * 50)
        candidates = korean_name_to_english(name)
        for i, candidate in enumerate(candidates, 1):
            print(f"{i}. {candidate}")